language: node_js
node_js:
  - '10.15.3'

jdk:
  - oraclejdk8

addons:
  sonarcloud:
    organization: "felipem4398-github" # the key of the org you chose at step #3
    token:
      secure: $SONAR_TOKEN # encrypted value of your tokenue

branches:
  only:
    - master

addons:
  chrome: stable

before_script:
 - npm install -g @angular/cli

cache:
  directories:
    - node_modules

script:
  - ng lint
  - ng test
  - sonar-scanner
  - ng build --prod
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB
  local_dir: ./dist/ChampionsLeagueApp
  on:
    branch: master
