language: node_js
node_js:
  - '10.15.3'

jdk:
  - oraclejdk8

branches:
  only:
    - master

addons:
  chrome: stable
  sonarcloud: true

before_script:
 - npm install -g @angular/cli

cache:
  directories:
    - node_modules

script:
  - ng lint
  - ng test
  - ng build --prod
  - sonar-scanner -Dsonar.login=$SONAR_TOKEN -Dsonar.organization=felipem4398-github -Dsonar.projectKey=FelipeM4398_prueba -Dsonar.sources='./src' -X
  
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB
  local_dir: ./dist/ChampionsLeagueApp
  on:
    branch: master
